
package step.example.flight.wsdl;

import javax.xml.ws.WebFault;
import step.example.flight.wsdl.FlightFault;
import step.example.flight.wsdl.FlightFault_Exception;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "flightFault", targetNamespace = "urn:step:example:flight:wsdl")
public class FlightFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FlightFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FlightFault_Exception(String message, FlightFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FlightFault_Exception(String message, FlightFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: step.example.flight.wsdl.FlightFault
     */
    public FlightFault getFaultInfo() {
        return faultInfo;
    }

}
