/**
 *  Flight Performance run instance config
 *  (syntax http://groovy.codehaus.org/ConfigSlurper)
 */

perf {
    flight {
        run {
            instance {
                id = "test"

                loadId = "test"

                configId = ""
                configToApplyList = [ "layermon" ]

                numberSamples = 2
                numberUsersPerSample = 1

                saveLog = true

                perfLogFormat = "layermon"
            }
        }
    }
}
