/**
 *  Flight Performance run instance config
 *  (syntax http://groovy.codehaus.org/ConfigSlurper)
 */

perf {
    flight {
        run {
            instance {
                loadId = "test"
                configId = "ehcachereadonly"
                applyConfigList = [ "layermon", "ehcachereadonly" ]

                numberSamples = 2

                saveLog = true

                perfLogFormat = "layermon"
            }
        }
    }
}
