//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.08 at 02:45:10 PM BST 
//


package step.example.mediator.view;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import step.example.mediator.view.ObjectFactory;
import step.example.mediator.view.ReservationView;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the step.example.mediator.view package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReservationView_QNAME = new QName("urn:step:example:mediator:view", "reservationView");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: step.example.mediator.view
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReservationView }
     * 
     */
    public ReservationView createReservationView() {
        return new ReservationView();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReservationView }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:step:example:mediator:view", name = "reservationView")
    public JAXBElement<ReservationView> createReservationView(ReservationView value) {
        return new JAXBElement<ReservationView>(_ReservationView_QNAME, ReservationView.class, null, value);
    }

}
