//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.08 at 02:45:10 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:step:example:mediator:view")
package step.example.mediator.view;
