//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.02 at 11:04:26 AM AZOST 
//


package step.framework.extensions.pipe.policy.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the step.framework.extensions.pipe.policy.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Smartstep_QNAME = new QName("http://stepframework.sourceforge.net/smartstep", "smartstep");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: step.framework.extensions.pipe.policy.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSSection }
     * 
     */
    public WSSection createWSSection() {
        return new WSSection();
    }

    /**
     * Create an instance of {@link WSDLDefinition }
     * 
     */
    public WSDLDefinition createWSDLDefinition() {
        return new WSDLDefinition();
    }

    /**
     * Create an instance of {@link WSClientSection }
     * 
     */
    public WSClientSection createWSClientSection() {
        return new WSClientSection();
    }

    /**
     * Create an instance of {@link ServiceSection }
     * 
     */
    public ServiceSection createServiceSection() {
        return new ServiceSection();
    }

    /**
     * Create an instance of {@link SmartSTEPConfig }
     * 
     */
    public SmartSTEPConfig createSmartSTEPConfig() {
        return new SmartSTEPConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmartSTEPConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://stepframework.sourceforge.net/smartstep", name = "smartstep")
    public JAXBElement<SmartSTEPConfig> createSmartstep(SmartSTEPConfig value) {
        return new JAXBElement<SmartSTEPConfig>(_Smartstep_QNAME, SmartSTEPConfig.class, null, value);
    }

}
