//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.23 at 01:31:53 PM WEST 
//


package step.framework.extensions.pipe.policy.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SmartSTEPConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SmartSTEPConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="service" type="{http://stepframework.sourceforge.net/smartstep}ServiceSection" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="wsclient" type="{http://stepframework.sourceforge.net/smartstep}WSClientSection" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ws" type="{http://stepframework.sourceforge.net/smartstep}WSSection" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SmartSTEPConfig", propOrder = {
    "service",
    "wsclient",
    "ws"
})
public class SmartSTEPConfig {

    protected List<ServiceSection> service;
    protected List<WSClientSection> wsclient;
    protected List<WSSection> ws;

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceSection }
     * 
     * 
     */
    public List<ServiceSection> getService() {
        if (service == null) {
            service = new ArrayList<ServiceSection>();
        }
        return this.service;
    }

    /**
     * Gets the value of the wsclient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsclient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWsclient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WSClientSection }
     * 
     * 
     */
    public List<WSClientSection> getWsclient() {
        if (wsclient == null) {
            wsclient = new ArrayList<WSClientSection>();
        }
        return this.wsclient;
    }

    /**
     * Gets the value of the ws property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ws property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WSSection }
     * 
     * 
     */
    public List<WSSection> getWs() {
        if (ws == null) {
            ws = new ArrayList<WSSection>();
        }
        return this.ws;
    }

}
