/**
 *  Flight Performance run instance config
 *  (syntax http://groovy.codehaus.org/ConfigSlurper)
 */

perf {
    flight {
        run {
            instance {
                loadId = "medium"
                configId = "eventmon"
                applyConfigList = [ "eventmon" ]

                numberSamples = 30

                saveLog = false

                perfLogFormat = "eventmon"
            }
        }
    }
}
